### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by yunginnanet**

### CODE REVIEW

**Review by didrocks — CHANGES_REQUESTED** [review]
Thanks for your contribution for improving zsys!

This part of the readme is autogenerated by our CI. To make thus those changes permanent, we need to have the CI part changed. Do you mind having a look there?

**Comment by yunginnanet** [comment]
> Thanks for your contribution for improving zsys!
> 
> This part of the readme is autogenerated by our CI. To make thus those changes permanent, we need to have the CI part changed. Do you mind having a look there?

I had a feeling that was the case, I'll take a look soon!

**Comment by yunginnanet** [comment]
Give that a whirl.

**Review by didrocks — COMMENTED** [review]
Hey! Thanks for giving this a try.

You code changes looks good, I have 2 requests before merging this:
- can you remove the changes that are not related to this PR? Like the `.gitignore` and `go.sum `ones.
- for `README.md`, I see the final result, which looks good! Can you remove the change though, as once we merged in main, a PR will be automatically created from the CI with the changes and be merged?

(Then, you or I, add your convienience, will squash this in a single commit)

Thanks in advance!

**Review by didrocks — APPROVED** [review]
Excellent, thanks a lot for this work and your contribution here! Merging :)

**Comment by yunginnanet** [comment]
Looks like we  now have a seemingly unrelated issue with the workflow

**Pull request merged**
